export const barFlavdata=[
    {
        id:1,
        flavour:"Merry Creme (Limited Edition)",
        desc:"Delicious flavours of pistachio and red velvet with our all new, .",
        price:40,
        image:"MerryCremeBars",
        qty:1,
        },
        {
        id:2,
        flavour:"Tripes",
        desc:"A blend of lime, orange and mint for triple the fun",
        price:45,
        image:"BarsTriples",
        qty:1,
        },
        {
        id:3,
        flavour:"Popitos",
        desc:"A little raw mango tanginess with a hint of sweetness",
        price:65,
        image:"BarsPopitos",
        qty:1,
        },
        {
        id:4,
        flavour:"An explosive coming together of pineapple and jamun",
        desc:"Bazooka",
        price:30,
        image:"BarsBazooka",
        qty:1,
        },
        {
        id:5,
        flavour:"Neapolitan Bar",
        desc:"Three yummy flavours in one stick - vanilla, strawberry and chocolate.",
        price:35,
        image:"neopolitanbar",
        qty:1,
        },
        {
        id:6,
        flavour:"Spiral-Wildberry,Vanilla&P-apple",
        desc:"wildberry, vanilla & pineapple - get blissfully lost amidst the spiral flavours.",
        price:30,
        image:"spiral-wildberry-vanilla-pinepple",
        qty:1,
        },
        {
        id:7,
        flavour:"Smiley",
        desc:"A Chocolate & Butterscotch flavoured ice cream bar",
        price:40,
        image:"SmileyBar",
        qty:1,
        },
        {
        id:8,
        flavour:"Watermelon",
        desc:"A pista and watermelon flavoured delight, perfect for summer.",
        price:40,
        image:"water-lemon",
        qty:1,
        },
       
        {
        id:9,
        flavour:"Chocobar",
        desc:"Get mesmerized with our chocobar - a popular favourite",
        price:30,
        image:"chocolatebar",
        qty:1,
        },
]