# Generated by Django 4.1.5 on 2023-02-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cups',
            name='cup_image',
            field=models.ImageField(default=1, upload_to='cupimages'),
            preserve_default=False,
        ),
    ]
