# Generated by Django 4.1.5 on 2023-02-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ibars'),
    ]

    operations = [
        migrations.CreateModel(
            name='IBarMini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibarmini_image', models.ImageField(upload_to='ibarminiimages')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
